# Error handling    

## Try/Except  

### Example  
        myStuff = []  

        try:  
            f.open("Stuff.mine","r")  
            myStuff = eval(f.read())  
            f.close()  

        except:  
            print("ERROR: Unable to load")  

        for row in myStuff:  
            print(row)  

> Try to find a file called 'Stuff.mine' and open it  
> If the file can't be found, show the error instead of crashing the whole program  

---  

### Example  
- We could even get rid of the 'err' variable entirely and print a traceback, which will show you the red error tracing you see when python crashes.  
- I've created a 'debugMode' variable at the top of my code and put the traceback in an if inside the except.  
- This lets me show/hide the tracebacks easily by setting debugMode to True/False.  

        myStuff = []  

        try:  
            f.open("Stuff.mine","r")  
            myStuff = eval(f.read())  
            f.close()  

        except Exception as err:  
            print("ERROR: Unable to load")  
            print(err)  

        for row in myStuff:  
            print(row)  

---

